---
title: "problem3"
author: "Subhashree Saha"
date: "2022-11-15"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(scales)

```
Comparison of the three models:\
```{r}
data_q3 <- faithful %>% 
  as_tibble()
x <- sort(data_q3$waiting)
```
1)MODEL 1\
```{r}
data_q3 <- faithful %>% 
  as_tibble()
x <- sort(data_q3$waiting)

# model 1
hist(x, xlab = 'waiting', probability = T, col='light blue', main='')
p <- length(x[x<65])/length(x)
x1 <- mean(x[x<65])
y1 <- var(x[x<65])
scale_1 <- y1/x1
shape_1<- x1/scale_1
mean1 <- mean(x[x>=65])
sd1 <- sd(x[x>=65])

Newloglike <- function(theta, data){
  n = length(data)
  
  p = theta[1]
  mu1 = theta[2]
  sig1 = theta[3]
  mu2 = theta[4]
  sig2 = theta[5]
  
  l = 0
  for (i in 1:n) {
    l = l + log(p*dgamma(data[i], shape = mu1, scale = sig1) + (1-p)*dnorm(data[i], mean = mu2, sd = sig2))
  }
  return(-l)
}
theta_inital <- c(p, shape_1, scale_1, mean1, sd1)
fit = optim(theta_inital,
            Newloglike,
            data = x,
            control = list(maxit = 1500),
            lower = c(0, 0, 0, -Inf, 0),
            upper = c(1, Inf, Inf, Inf, Inf),
            method="L-BFGS-B")
theta_1 = fit$par

p1=theta_1[1]
mu1 = theta_1[2]
sig1 = theta_1[3]
mu2 = theta_1[4]
sig2 = theta_1[5]

model_1 = p1*dgamma(x, shape = mu1, scale = sig1) + (1-p1)*dnorm(x, mean = mu2, sd = sig2)
lines(x,model_1,lwd=3,col='purple')
aic_1 <- 2*5 + Newloglike(theta_1, x)
```
2)Model2\
```{r}
# model 2
hist(x, xlab = 'waiting', probability = T, col='pink', main='')
p <- length(x[x<65])/length(x)
x21 <- mean(x[x<65])
y21 <- var(x[x<65])
scale_21 <- y21/x21
shape_21 <- x21/scale_21
x22 <- mean(x[x>=65])
y22 <- var(x[x>=65])
scale_22 <- y22/x22
shape_22<- x22/scale_22
theta_inital2 <- c(p, shape_21,scale_21 , shape_22, scale_22)
Newloglike2 <- function(theta, data){
  n <- length(data)
  
  p = theta[1]
  mu1 = theta[2]
  sig1 = theta[3]
  mu2 = theta[4]
  sig2 = theta[5]
  
  l <- 0
  for (i in 1:n) {
    l = l + log(p*dgamma(data[i], shape = mu1, scale = sig1) + (1-p)*dgamma(data[i], shape = mu2, scale = sig2))
  }
  return(-l)
}
fit2 = optim(theta_inital2,
             Newloglike2,
            data = x,
            control = list(maxit = 1500),
            lower = c(0, 0, 0, 0, 0),
            upper = c(1, Inf, Inf, Inf, Inf),
            method="L-BFGS-B")
theta_2 <- fit2$par
theta_2
p2=theta_2[1]
mu12 = theta_2[2]
sig12 = theta_2[3]
mu22 = theta_2[4]
sig22 = theta_2[5]
model_2 <- p2*dgamma(x, shape = mu12, scale = sig12) + (1-p2)*dgamma(x, shape = mu22, scale = sig22)
lines(x,model_2,lwd=3,col='purple')
aic_2 <- 2*5 + Newloglike2(theta_2, x)
```
3)Model3\
```{r}
hist(x, xlab = 'waiting', probability = T, col='light green', main='')
p <- length(x[x<65])/length(x)
x31 <- mean(x[x<65])
y31 <- var(x[x<65])
var31 <- log((y31/x31^2) + 1)
mean31 <- log(x31) - var31/2
x32 <- mean(x[x>=65])
y32 <- var(x[x>=65])
var32<- log((y32/x32^2) + 1)
mean32 <- log(x32) - var32/2
theta_inital3 <- c(p, mean31, sqrt(var31), mean32, sqrt(var32))
Newloglike3 <- function(theta, data) {
  n <- length(data)
  
  p = theta[1]
  mu1 = theta[2]
  sig1 = theta[3]
  mu2 = theta[4]
  sig2 = theta[5]
  
  l <- 0
  for (i in 1:n) {
    l = l + log(p*dlnorm(data[i], meanlog = mu1, sdlog = sig1) + (1-p)*dlnorm(data[i], meanlog = mu2, sdlog = sig2))
  }
  
  return(-l)
}
fit3 = optim(theta_inital3,
             Newloglike3,
            data = x,
            control = list(maxit = 1500),
            lower = c(0, -Inf, 0, -Inf, 0),
            upper = c(1, Inf, Inf, Inf, Inf),
            method="L-BFGS-B")
theta_3 <- fit3$par

p3 <- theta_3[1]
mu13 <- theta_3[2]
sig13 <- theta_3[3]
mu23 <- theta_3[4]
sig23 <- theta_3[5]
model_3 <- p3*dlnorm(x, meanlog = mu13, sdlog = sig13) + (1-p3)*dlnorm(x, meanlog = mu23, sdlog = sig23)
lines(x,model_3,lwd=3,col='purple')
aic_3 <- 2*5 + Newloglike3(theta_3, x)
```

AIC for the three models are:

```{r}
aic_1
aic_2
aic_3
```
Based on the above three models,model3 has the best fit since it has the lowest AIC\

Therefore based on model3, P(60<waiting<70) is
```{r}
q=(p3*plnorm(70, meanlog = mu13, sdlog = sig13) + (1-p3)*plnorm(70, meanlog = mu23, sdlog = sig23)) - (p3*plnorm(60, meanlog = mu13, sdlog = sig13) + (1-p3)*plnorm(60, meanlog = mu23, sdlog = sig23))
q                                                                                                     
```



